//! CML-EXHAUSTIVE-IR-CLASSIFICATION-TEST (FPGA + C, no x86 dependency).
//!
//! Every Ir / Quoted variant must be either successfully emitted or rejected
//! with a typed error — never a panic. Writes a durable matrix artifact under
//! evidence/semantic-ir-recovery/ for SEMANTIC-IR-RECOVERY-M0.

use cml::c_backend::CBackend;
use cml::compiler::Compiler;
use cml::ir::{BufferLiteral, Ir, Params, PrimOp, Quoted};
use std::fs;
use std::panic;
use std::path::PathBuf;

fn all_quoted() -> Vec<Quoted> {
    vec![
        Quoted::Int(42),
        Quoted::Float(3.14),
        Quoted::Rational(1, 2),
        Quoted::Sym("foo".to_string()),
        Quoted::Str("bar".to_string()),
        Quoted::Nil,
        Quoted::List(vec![Quoted::Int(1)]),
        Quoted::DottedList(vec![Quoted::Int(1)], Box::new(Quoted::Int(2))),
    ]
}

fn all_ir() -> Vec<(String, Ir)> {
    let mut irs = vec![
        ("Int", Ir::Int(42)),
        ("Float", Ir::Float(3.14)),
        ("Rational", Ir::Rational(1, 2)),
        ("String", Ir::String("hello".to_string())),
        ("BufferI32", Ir::Buffer(BufferLiteral::I32(vec![1, 2, 3]))),
        ("BufferF32", Ir::Buffer(BufferLiteral::F32(vec![1, 2, 3]))),
        ("Nil", Ir::Nil),
        ("True", Ir::True),
        ("Var", Ir::Var("x".to_string())),
        ("Builtin", Ir::Builtin("car".to_string())),
        (
            "Lambda",
            Ir::Lambda {
                params: Params::Fixed(vec![]),
                body: Box::new(Ir::Nil),
            },
        ),
        (
            "App",
            Ir::App {
                func: Box::new(Ir::Var("f".to_string())),
                args: vec![],
            },
        ),
        (
            "Cond",
            Ir::Cond {
                branches: vec![(Ir::True, Ir::Int(1))],
            },
        ),
        (
            "Let",
            Ir::Let {
                bindings: vec![("x".to_string(), Ir::Int(1))],
                body: Box::new(Ir::Var("x".to_string())),
            },
        ),
        (
            "Def",
            Ir::Def {
                name: "f".to_string(),
                value: Box::new(Ir::Lambda {
                    params: Params::Fixed(vec![]),
                    body: Box::new(Ir::Nil),
                }),
            },
        ),
        (
            "Prim",
            Ir::Prim {
                op: PrimOp::Add,
                args: vec![Ir::Int(1), Ir::Int(2)],
            },
        ),
        (
            "TailSelfCall",
            Ir::TailSelfCall {
                args: vec![Ir::Int(1)],
            },
        ),
    ]
    .into_iter()
    .map(|(n, i)| (n.to_string(), i))
    .collect::<Vec<_>>();

    for q in all_quoted() {
        let label = match &q {
            Quoted::Int(_) => "Quote(Int)",
            Quoted::Float(_) => "Quote(Float)",
            Quoted::Rational(_, _) => "Quote(Rational)",
            Quoted::Sym(_) => "Quote(Sym)",
            Quoted::Str(_) => "Quote(Str)",
            Quoted::Nil => "Quote(Nil)",
            Quoted::List(_) => "Quote(List)",
            Quoted::DottedList(_, _) => "Quote(DottedList)",
        };
        irs.push((label.to_string(), Ir::Quote(q)));
    }
    irs
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum Class {
    Emitted,
    Rejected(String),
}

fn classify_fpga(ir: &Ir) -> Class {
    match panic::catch_unwind(|| Compiler::new().compile(&[ir.clone()])) {
        Ok(Ok(_)) => Class::Emitted,
        Ok(Err(e)) => Class::Rejected(e.to_string()),
        Err(_) => panic!("FPGA panicked on {ir:?}"),
    }
}

fn classify_c(ir: &Ir) -> Class {
    match panic::catch_unwind(|| CBackend::new().compile_program(&[ir.clone()])) {
        Ok(Ok(_)) => Class::Emitted,
        Ok(Err(e)) => Class::Rejected(e.to_string()),
        Err(_) => panic!("C backend panicked on {ir:?}"),
    }
}

fn class_tag(c: &Class) -> &'static str {
    match c {
        Class::Emitted => "emitted",
        Class::Rejected(_) => "rejected",
    }
}

#[test]
fn every_ir_variant_is_classified_by_fpga_and_c_without_panic() {
    let variants = all_ir();
    assert!(
        variants.len() >= 17 + 8,
        "expected all IR + Quote wrappers, got {}",
        variants.len()
    );

    let mut lines = vec![
        "; ir-classification-matrix.my — generated by tests/ir_classification_matrix_test.rs".into(),
        "; Every row is Emitted or RejectedTypedError; panic fails the test.".into(),
        "((kind . ir-classification-matrix)".into(),
        " (date . \"2026-09-09\")".into(),
        " (backends . (fpga-lisp c-backend))".into(),
        " (rows . (".into(),
    ];

    let mut fpga_emit = 0usize;
    let mut fpga_rej = 0usize;
    let mut c_emit = 0usize;
    let mut c_rej = 0usize;

    for (name, ir) in &variants {
        let fpga = classify_fpga(ir);
        let c = classify_c(ir);
        match &fpga {
            Class::Emitted => fpga_emit += 1,
            Class::Rejected(_) => fpga_rej += 1,
        }
        match &c {
            Class::Emitted => c_emit += 1,
            Class::Rejected(_) => c_rej += 1,
        }
        let fpga_detail = match &fpga {
            Class::Emitted => "ok".to_string(),
            Class::Rejected(e) => e.replace('"', "'"),
        };
        let c_detail = match &c {
            Class::Emitted => "ok".to_string(),
            Class::Rejected(e) => e.replace('"', "'"),
        };
        lines.push(format!(
            "  ({name} . ((fpga . {}) (fpga-detail . \"{fpga_detail}\") (c . {}) (c-detail . \"{c_detail}\")))",
            class_tag(&fpga),
            class_tag(&c)
        ));
    }

    lines.push(" ))".into());
    lines.push(format!(
        " (summary . ((fpga-emitted . {fpga_emit}) (fpga-rejected . {fpga_rej}) (c-emitted . {c_emit}) (c-rejected . {c_rej}) (variants . {})))",
        variants.len()
    ));
    lines.push(")".into());

    assert!(fpga_emit > 0 && fpga_rej > 0, "FPGA must emit and reject");
    assert!(c_emit > 0 && c_rej > 0, "C must emit and reject");

    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("evidence/semantic-ir-recovery");
    let _ = fs::create_dir_all(&dir);
    let path = dir.join("ir-classification-matrix.my");
    fs::write(&path, lines.join("\n") + "\n").expect("write matrix artifact");
    assert!(path.exists(), "matrix artifact must exist at {path:?}");
}

#[test]
fn fpga_rejects_unimplemented_with_unsupported_prefix() {
    for (name, ir) in [
        ("Builtin", Ir::Builtin("car".into())),
        ("Rational", Ir::Rational(1, 2)),
        ("Float", Ir::Float(1.0)),
        ("TailSelfCall", Ir::TailSelfCall { args: vec![] }),
        ("QuoteFloat", Ir::Quote(Quoted::Float(1.0))),
    ] {
        match classify_fpga(&ir) {
            Class::Rejected(e) => assert!(
                e.contains("Unsupported") || e.contains(name) || e.contains("NumericOverflow"),
                "{name}: unexpected rejection text {e}"
            ),
            Class::Emitted => panic!("{name} must not emit on FPGA yet"),
        }
    }
}
