(evidence
  (fixture . "(def length-onto (lambda (values acc) (cond ((atom values) acc) (t (length-onto (cdr values) (+ acc 1)))))) (def length (lambda (values) (length-onto values 0))) (length (quote (a b c)))")
  (requirement . length-e2e)
  (implementation . my-lisp)
  (commit . "bb6a595")
  (runner . tcp-oracle)
  (expected . "3")
  (actual . "3")
  (result . pass)
  (timestamp . "2026-08-12")
  (note . "reference value for evidence/length/cml/26c1963.my and evidence/length/fpga-lisp/735e7c4.my, obtained live from the my-lisp --tcp=9999 --protocol=sexpr oracle (this exact source, unmodified, in its own isolated connection environment). Recorded from the cml side since cml ran the comparison; my-lisp's own evidence dir may carry an equivalent record independently."))
