; Generated by juv4uk/sens/.github/workflows/sync-language-contract.yml
; This pins the observed upstream authority. It does NOT claim that the
; consumer implements the pinned contract version.
(contract-lock
  (source
    (repository juv4uk/sens)
    (branch main)
    (path language-contract.lisp))
  (revision "07643eeb91cc039ef63b351476c8519442f4aa51")
  (sha256 "d60d96dfbe35910588cc0848d0b3ea8da5d7af8a901b7c39bfc7fb6eb6c0ebe3"))
