; Generated by juv4uk/sens/.github/workflows/sync-language-contract.yml
; This pins the observed upstream authority. It does NOT claim that the
; consumer implements the pinned contract version.
(contract-lock
  (source
    (repository juv4uk/sens)
    (branch main)
    (path language-contract.lisp))
  (revision "7283342213ff78c483eed20b5f72dafeb56a5916")
  (sha256 "aaaa9fecf72da3cf30e30cc52a0b6e379913f4e0ec788e367453838680cb493f"))
