; cml-operations.lisp — machine-readable table of CML operations and Canon projections
; Generated at build time from sens/lib/surface/semantic-registry.lisp. DO NOT EDIT BY HAND.

((kind . cml-operations-table)
 (version . (1 0))
 (authority . ((language . juv4uk/my-lisp)
               (compiler . juv4uk/cml)))
 (operations
  . (((canonical-name . "quote")
      (semantic-id . "00000001")
      (formal-action . "syntax:quote")
      (surfaces . ((en . "quote") (ук . "як-є") (укр . "як-є") (sa . "svarūpa") (sym . "\"'\"")))
      (cml-ir-projection . "Ir::Quote")
      (backend-projections . ((fpga-lisp . "LOADSYM/QUOTE") (c . "TAG_QUOTE/mk_pair") (x86_freestanding . "literal_encoding")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/canon_dispatch_test.rs"))
     ((canonical-name . "atom?")
      (semantic-id . "00000010")
      (formal-action . "primitive:atom")
      (surfaces . ((en . "atom?") (ук . "атом?") (укр . "атом?") (sa . "aṇu") (sym . ".?")))
      (cml-ir-projection . "Ir::App(Sid(00000010))")
      (backend-projections . ((fpga-lisp . "OP_ATOM") (c . "prim_atom") (x86_freestanding . "wsm_atom")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "eq?")
      (semantic-id . "00000011")
      (formal-action . "primitive:eq")
      (surfaces . ((en . "eq?") (ук . "тотожне?") (укр . "тотожне?") (sa . "abheda") (sym . "=?")))
      (cml-ir-projection . "Ir::App(Sid(00000011))")
      (backend-projections . ((fpga-lisp . "OP_EQ") (c . "prim_eq") (x86_freestanding . "wsm_eq")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "cons")
      (semantic-id . "00000100")
      (formal-action . "primitive:cons")
      (surfaces . ((en . "cons") (ук . "сполучити") (укр . "сполучити") (sa . "saṃyuj") (sym . ":")))
      (cml-ir-projection . "Ir::App(Sid(00000100))")
      (backend-projections . ((fpga-lisp . "OP_CONS") (c . "mk_cons") (x86_freestanding . "wsm_cons")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "car")
      (semantic-id . "00000101")
      (formal-action . "primitive:car")
      (surfaces . ((en . "car") (ук . "перше") (укр . "перше") (sa . "ādi") (sym . ":п")))
      (cml-ir-projection . "Ir::App(Sid(00000101))")
      (backend-projections . ((fpga-lisp . "OP_CAR") (c . "v_car") (x86_freestanding . "wsm_car")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "cdr")
      (semantic-id . "00000110")
      (formal-action . "primitive:cdr")
      (surfaces . ((en . "cdr") (ук . "решта") (укр . "решта") (sa . "śeṣa") (sym . ":р")))
      (cml-ir-projection . "Ir::App(Sid(00000110))")
      (backend-projections . ((fpga-lisp . "OP_CDR") (c . "v_cdr") (x86_freestanding . "wsm_cdr")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "cond")
      (semantic-id . "00000111")
      (formal-action . "syntax:cond")
      (surfaces . ((en . "cond") (ук . "за-умовою") (укр . "за-умовою") (sa . "anukrama") (sym . "?:")))
      (cml-ir-projection . "Ir::Cond")
      (backend-projections . ((fpga-lisp . "CJMP/JMP") (c . "if-else-chain") (x86_freestanding . "testq/jz")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/canon_dispatch_test.rs"))
     ((canonical-name . "lambda")
      (semantic-id . "00001000")
      (formal-action . "syntax:lambda")
      (surfaces . ((en . "lambda") (ук . "функція") (укр . "функція")))
      (cml-ir-projection . "Ir::Lambda")
      (backend-projections . ((fpga-lisp . "closure/alist-env") (c . "env_tuple_closure") (x86_freestanding . "closure_alloc/direct_call")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/canon_dispatch_test.rs"))
     ((canonical-name . "define")
      (semantic-id . "00001001")
      (formal-action . "syntax:define")
      (surfaces . ((en . "define") (ук . "визначити") (укр . "визначити")))
      (cml-ir-projection . "Ir::Def")
      (backend-projections . ((fpga-lisp . "top-level-binding") (c . "top_level_def") (x86_freestanding . "top_level_symbol")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/canon_dispatch_test.rs"))
     ((canonical-name . "def")
      (semantic-id . "00001011")
      (formal-action . "compatibility:def")
      (surfaces . ((en . "def")))
      (cml-ir-projection . "Ir::Def")
      (backend-projections . ((fpga-lisp . "top-level-binding") (c . "top_level_def") (x86_freestanding . "top_level_symbol")))
      (status . compatibility)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/canon_dispatch_test.rs"))
     ((canonical-name . "defmacro")
      (semantic-id . "00001010")
      (formal-action . "syntax:defmacro")
      (surfaces . ((en . "defmacro") (ук . "визначити-макрос") (укр . "визначити-макрос")))
      (cml-ir-projection . "macro_expansion")
      (backend-projections . ((fpga-lisp . "frontend_macro_expand") (c . "frontend_macro_expand") (x86_freestanding . "frontend_macro_expand")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/macro_pipeline_test.rs"))
     ((canonical-name . "plus")
      (semantic-id . "00001100")
      (formal-action . "primitive:add")
      (surfaces . ((en . "plus") (ук . "додати") (укр . "додати") (sa . "yoga") (sym . "+")))
      (cml-ir-projection . "Ir::App(Sid(00001100))")
      (backend-projections . ((fpga-lisp . "OP_ADD") (c . "prim_add") (x86_freestanding . "addq")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "difference")
      (semantic-id . "00001101")
      (formal-action . "primitive:sub")
      (surfaces . ((en . "difference") (ук . "відняти") (укр . "відняти") (sa . "viyoga") (sym . "-")))
      (cml-ir-projection . "Ir::App(Sid(00001101))")
      (backend-projections . ((fpga-lisp . "OP_SUB") (c . "prim_sub") (x86_freestanding . "subq")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "times")
      (semantic-id . "00001110")
      (formal-action . "primitive:exact-q-mul")
      (surfaces . ((en . "times") (ук . "помножити") (укр . "помножити") (sa . "guṇana") (sym . "*")))
      (cml-ir-projection . "Ir::App(Sid(00001110))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "unsupported") (x86_freestanding . "unsupported")))
      (status . partial)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/exact_q_mul_admission_test.rs"))
     ((canonical-name . "mod")
      (semantic-id . "00010011")
      (formal-action . "primitive:exact-q-mod")
      (surfaces . ((en . "mod") (ук . "остача") (укр . "остача") (sa . "avasiṣṭa")))
      (cml-ir-projection . "Ir::App(Sid(00010011))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "unsupported") (x86_freestanding . "unsupported")))
      (status . partial)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/exact_q_mod_admission_test.rs"))
     ((canonical-name . "divide")
      (semantic-id . "00001111")
      (formal-action . "primitive:exact-q-div")
      (surfaces . ((en . "divide") (ук . "поділити") (укр . "поділити") (sa . "haraṇa") (sym . "/")))
      (cml-ir-projection . "Ir::App(Sid(00001111))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "unsupported") (x86_freestanding . "unsupported")))
      (status . partial)
      (authority-owner . "sens:exact-q-binary cml:compiler-middle-end")
      (provenance-witness . "sens/contracts/exact-q-binary-contract.lisp tests/exact_q_div_admission_test.rs"))
     ((canonical-name . "quotient")
      (semantic-id . "00010100")
      (formal-action . "primitive:exact-q-quotient")
      (surfaces . ((en . "quotient") (ук . "частка") (укр . "частка") (sa . "bhāga")))
      (cml-ir-projection . "Ir::App(Sid(00010100))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "unsupported") (x86_freestanding . "unsupported")))
      (status . partial)
      (authority-owner . "sens:exact-q-binary cml:compiler-middle-end")
      (provenance-witness . "sens/contracts/exact-q-binary-contract.lisp tests/exact_q_quotient_admission_test.rs"))
     ((canonical-name . "lessp?")
      (semantic-id . "00011010")
      (formal-action . "primitive:exact-q-less-than")
      (surfaces . ((en . "lessp?") (ук . "менше?") (укр . "менше?") (sa . "hīna?") (sym . "<")))
      (cml-ir-projection . "Ir::App(Sid(00011010))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "v_exact_q_lt/builtin_exact_q_lt") (x86_freestanding . "unsupported")))
      (status . partial)
      (authority-owner . "sens:exact-q-binary cml:compiler-middle-end")
      (provenance-witness . "sens/contracts/exact-q-binary-contract.lisp tests/exact_q_compare_lowering_test.rs tests/exact_q_lt_encoder_consumer_test.rs"))
     ((canonical-name . "greaterp?")
      (semantic-id . "00011011")
      (formal-action . "primitive:exact-q-greater-than")
      (surfaces . ((en . "greaterp?") (ук . "більше?") (укр . "більше?") (sa . "adhika?") (sym . ">")))
      (cml-ir-projection . "Ir::App(Sid(00011011))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "unsupported") (x86_freestanding . "unsupported")))
      (status . partial)
      (authority-owner . "sens:exact-q-binary cml:compiler-middle-end")
      (provenance-witness . "sens/contracts/exact-q-binary-contract.lisp tests/exact_q_compare_lowering_test.rs"))
     ((canonical-name . "equalp?")
      (semantic-id . "00011100")
      (formal-action . "primitive:exact-q-equal")
      (surfaces . ((en . "equalp?") (ук . "рівне?") (укр . "рівне?") (sa . "sama?") (sym . "=")))
      (cml-ir-projection . "Ir::App(Sid(00011100))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "unsupported") (x86_freestanding . "unsupported")))
      (status . partial)
      (authority-owner . "sens:exact-q-binary cml:compiler-middle-end")
      (provenance-witness . "sens/contracts/exact-q-binary-contract.lisp tests/exact_q_compare_lowering_test.rs"))
     ((canonical-name . "not-greaterp?")
      (semantic-id . "00011101")
      (formal-action . "primitive:exact-q-less-equal")
      (surfaces . ((en . "not-greaterp?") (ук . "не-більше?") (укр . "не-більше?") (sa . "na-adhika?") (sym . "<=")))
      (cml-ir-projection . "Ir::App(Sid(00011101))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "unsupported") (x86_freestanding . "bounded-fixnum/numeric-0-or-1")))
      (status . partial)
      (authority-owner . "sens:exact-q-binary cml:compiler-middle-end")
      (provenance-witness . "sens/contracts/exact-q-binary-contract.lisp tests/exact_q_compare_lowering_test.rs"))
     ((canonical-name . "not-lessp?")
      (semantic-id . "00011110")
      (formal-action . "primitive:exact-q-greater-equal")
      (surfaces . ((en . "not-lessp?") (ук . "не-менше?") (укр . "не-менше?") (sa . "na-hīna?") (sym . ">=")))
      (cml-ir-projection . "Ir::App(Sid(00011110))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "unsupported") (x86_freestanding . "bounded-fixnum/numeric-0-or-1")))
      (status . partial)
      (authority-owner . "sens:exact-q-binary cml:compiler-middle-end")
      (provenance-witness . "sens/contracts/exact-q-binary-contract.lisp tests/exact_q_compare_lowering_test.rs"))
     ((canonical-name . "equal?")
      (semantic-id . "00100010")
      (formal-action . "primitive:equalp")
      (surfaces . ((en . "equal?") (ук . "однакові?") (укр . "однакові?") (sa . "tulya?")))
      (cml-ir-projection . "Ir::App(Sid(00100010))")
      (backend-projections . ((fpga-lisp . "cml_equal") (c . "prim_equalp") (x86_freestanding . "unsupported")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "numeric-buffer-map")
      (semantic-id . "01011001")
      (formal-action . "library:numeric-buffer-map")
      (surfaces . ((en . "numeric-buffer-map") (укр . "відобразити-числовий-буфер")))
      (cml-ir-projection . "Ir::App(Sid(01011001))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "cml_numeric_buffer_map") (x86_freestanding . "unsupported")))
      (status . supported)
      (authority-owner . "sens:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.lisp tests/c_backend_test.rs")))))
