; cml-operations.my — machine-readable table of CML operations and Canon projections
; Generated at build time from my-lisp/lib/surface/semantic-registry.wsm. DO NOT EDIT BY HAND.

((kind . cml-operations-table)
 (version . (1 0))
 (authority . ((language . juv4uk/my-lisp)
               (compiler . juv4uk/cml)))
 (operations
  . (((canonical-name . "quote")
      (semantic-id . "0001")
      (formal-action . "syntax:quote")
      (surfaces . ((en . "quote") (uk . "як-є") (sa . "svarūpa") (sym . "'")))
      (cml-ir-projection . "Ir::Quote")
      (backend-projections . ((fpga-lisp . "LOADSYM/QUOTE") (c . "TAG_QUOTE/mk_pair") (x86_freestanding . "literal_encoding")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/canon_dispatch_test.rs"))
     ((canonical-name . "atom")
      (semantic-id . "0002")
      (formal-action . "primitive:atom")
      (surfaces . ((en . "atom") (uk . "атом?") (sa . "aṇu") (sym . ".?")))
      (cml-ir-projection . "Ir::Prim(PrimOp::Atom)")
      (backend-projections . ((fpga-lisp . "OP_ATOM") (c . "prim_atom") (x86_freestanding . "wsm_atom")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "eq")
      (semantic-id . "0003")
      (formal-action . "primitive:eq")
      (surfaces . ((en . "eq") (uk . "тотожне?") (sa . "abheda") (sym . "=?")))
      (cml-ir-projection . "Ir::Prim(PrimOp::Eq)")
      (backend-projections . ((fpga-lisp . "OP_EQ") (c . "prim_eq") (x86_freestanding . "wsm_eq")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "cons")
      (semantic-id . "0004")
      (formal-action . "primitive:cons")
      (surfaces . ((en . "cons") (uk . "сполучити") (sa . "saṃyuj") (sym . ":")))
      (cml-ir-projection . "Ir::Prim(PrimOp::Cons)")
      (backend-projections . ((fpga-lisp . "OP_CONS") (c . "mk_cons") (x86_freestanding . "wsm_cons")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "car")
      (semantic-id . "0005")
      (formal-action . "primitive:car")
      (surfaces . ((en . "car") (uk . "перше") (sa . "ādi") (sym . ":п")))
      (cml-ir-projection . "Ir::Prim(PrimOp::Car)")
      (backend-projections . ((fpga-lisp . "OP_CAR") (c . "v_car") (x86_freestanding . "wsm_car")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "cdr")
      (semantic-id . "0006")
      (formal-action . "primitive:cdr")
      (surfaces . ((en . "cdr") (uk . "решта") (sa . "śeṣa") (sym . ":р")))
      (cml-ir-projection . "Ir::Prim(PrimOp::Cdr)")
      (backend-projections . ((fpga-lisp . "OP_CDR") (c . "v_cdr") (x86_freestanding . "wsm_cdr")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "cond")
      (semantic-id . "0007")
      (formal-action . "syntax:cond")
      (surfaces . ((en . "cond") (uk . "за-умовою") (sa . "anukrama") (sym . "?:")))
      (cml-ir-projection . "Ir::Cond")
      (backend-projections . ((fpga-lisp . "CJMP/JMP") (c . "if-else-chain") (x86_freestanding . "testq/jz")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/canon_dispatch_test.rs"))
     ((canonical-name . "lambda")
      (semantic-id . "0010")
      (formal-action . "syntax:lambda")
      (surfaces . ((en . "lambda") (uk . "функція")))
      (cml-ir-projection . "Ir::Lambda")
      (backend-projections . ((fpga-lisp . "closure/alist-env") (c . "env_tuple_closure") (x86_freestanding . "closure_alloc/direct_call")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/canon_dispatch_test.rs"))
     ((canonical-name . "define")
      (semantic-id . "0011")
      (formal-action . "syntax:define")
      (surfaces . ((en . "define") (uk . "визначити")))
      (cml-ir-projection . "Ir::Def")
      (backend-projections . ((fpga-lisp . "top-level-binding") (c . "top_level_def") (x86_freestanding . "top_level_symbol")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/canon_dispatch_test.rs"))
     ((canonical-name . "def")
      (semantic-id . "1000")
      (formal-action . "compatibility:def")
      (surfaces . ((en . "def")))
      (cml-ir-projection . "Ir::Def")
      (backend-projections . ((fpga-lisp . "top-level-binding") (c . "top_level_def") (x86_freestanding . "top_level_symbol")))
      (status . compatibility)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/canon_dispatch_test.rs"))
     ((canonical-name . "defmacro")
      (semantic-id . "0012")
      (formal-action . "syntax:defmacro")
      (surfaces . ((en . "defmacro") (uk . "визначити-макрос")))
      (cml-ir-projection . "macro_expansion")
      (backend-projections . ((fpga-lisp . "frontend_macro_expand") (c . "frontend_macro_expand") (x86_freestanding . "frontend_macro_expand")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/macro_pipeline_test.rs"))
     ((canonical-name . "+")
      (semantic-id . "0104")
      (formal-action . "primitive:add")
      (surfaces . ((uk . "додати") (sa . "yoga") (sym . "+")))
      (cml-ir-projection . "Ir::Prim(PrimOp::Add)")
      (backend-projections . ((fpga-lisp . "OP_ADD") (c . "prim_add") (x86_freestanding . "addq")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "-")
      (semantic-id . "1001")
      (formal-action . "primitive:sub")
      (surfaces . ((uk . "відняти") (sa . "viyoga") (sym . "-")))
      (cml-ir-projection . "Ir::Prim(PrimOp::Sub)")
      (backend-projections . ((fpga-lisp . "OP_SUB") (c . "prim_sub") (x86_freestanding . "subq")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "equal?")
      (semantic-id . "1022")
      (formal-action . "primitive:equalp")
      (surfaces . ((en . "equal?") (uk . "однакові?") (sa . "tulya?")))
      (cml-ir-projection . "Ir::Prim(PrimOp::EqualP)")
      (backend-projections . ((fpga-lisp . "cml_equal") (c . "prim_equalp") (x86_freestanding . "unsupported")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/registry_driven_canon_callables_test.rs"))
     ((canonical-name . "numeric-buffer-map")
      (semantic-id . "1074")
      (formal-action . "library:numeric-buffer-map")
      (surfaces . ((en . "numeric-buffer-map")))
      (cml-ir-projection . "Ir::App(Builtin(\"NUMERIC-BUFFER-MAP\"))")
      (backend-projections . ((fpga-lisp . "unsupported") (c . "cml_numeric_buffer_map") (x86_freestanding . "unsupported")))
      (status . supported)
      (authority-owner . "my-lisp:language-core cml:compiler-middle-end")
      (provenance-witness . "lib/surface/semantic-registry.wsm tests/c_backend_test.rs")))))
