(cml-export/1
  (contract (major 6) (minor 0))
  (digest "22f673f2d2bc3d28")
  (forms
    (00000000 (surfaces ) (role registry) (callable nil))
    (00000001 (surfaces (en "quote") (sa "svarūpa") (sym "'") (uk "як-є") (ukr "як-є")) (role syntax) (callable nil))
    (00000010 (surfaces (en "atom") (sa "aṇu") (sym ".?") (uk "атом?") (ukr "атом?")) (role primitive) (callable t))
    (00000011 (surfaces (en "eq") (sa "abheda") (sym "=?") (uk "тотожне?") (ukr "тотожне?")) (role primitive) (callable t))
    (00000100 (surfaces (en "cons") (sa "saṃyuj") (sym ":") (uk "сполучити") (ukr "сполучити")) (role primitive) (callable t))
    (00000101 (surfaces (en "car") (sa "ādi") (sym ":п") (uk "перше") (ukr "перше")) (role primitive) (callable t))
    (00000110 (surfaces (en "cdr") (sa "śeṣa") (sym ":р") (uk "решта") (ukr "решта")) (role primitive) (callable t))
    (00000111 (surfaces (en "cond") (sa "anukrama") (sym "?:") (uk "за-умовою") (ukr "за-умовою")) (role syntax) (callable nil))
    (00001000 (surfaces (en "lambda") (uk "функція") (ukr "функція")) (role syntax) (callable nil))
    (00001001 (surfaces (en "define") (uk "визначити") (ukr "визначити")) (role syntax) (callable nil))
    (00001010 (surfaces (en "defmacro") (uk "визначити-макрос") (ukr "визначити-макрос")) (role syntax) (callable nil))
    (00001011 (surfaces (en "def")) (role registry) (callable nil))
    (00001100 (surfaces (sa "yoga") (sym "+") (uk "додати") (ukr "додати")) (role registry) (callable nil))
    (00001101 (surfaces (sa "viyoga") (sym "-") (uk "відняти") (ukr "відняти")) (role library) (callable t))
    (00001110 (surfaces (sa "guṇana") (sym "*") (uk "помножити") (ukr "помножити")) (role registry) (callable nil))
    (00001111 (surfaces (sa "haraṇa") (sym "/") (uk "поділити") (ukr "поділити")) (role registry) (callable nil))
    (00010000 (surfaces (en "abs") (sa "rūpa") (uk "модуль") (ukr "модуль")) (role registry) (callable nil))
    (00010001 (surfaces (en "min") (sa "alpatara") (uk "найменше") (ukr "найменше")) (role registry) (callable nil))
    (00010010 (surfaces (en "max") (sa "brhattara") (uk "найбільше") (ukr "найбільше")) (role registry) (callable nil))
    (00010011 (surfaces (en "mod") (sa "avasiṣṭa") (uk "остача") (ukr "остача")) (role registry) (callable nil))
    (00010100 (surfaces (en "quotient") (sa "bhāga") (uk "частка") (ukr "частка")) (role registry) (callable nil))
    (00010101 (surfaces (en "sqrt") (sa "mūla") (uk "корінь") (ukr "корінь")) (role registry) (callable nil))
    (00010110 (surfaces (en "isqrt") (sa "sakalamūla") (uk "цілий-корінь") (ukr "цілий-корінь")) (role registry) (callable nil))
    (00010111 (surfaces (en "min-list") (uk "найменше-у-списку") (ukr "найменше-у-списку")) (role registry) (callable nil))
    (00011000 (surfaces (en "max-list") (uk "найбільше-у-списку") (ukr "найбільше-у-списку")) (role registry) (callable nil))
    (00011001 (surfaces (en "largest-chunk") (ukr "найбільший-фрагмент")) (role registry) (callable nil))
    (00011010 (surfaces (sa "hīna?") (sym "<") (uk "менше?") (ukr "менше?")) (role registry) (callable nil))
    (00011011 (surfaces (sa "adhika?") (sym ">") (uk "більше?") (ukr "більше?")) (role registry) (callable nil))
    (00011100 (surfaces (sa "sama?") (sym "=") (uk "рівне?") (ukr "рівне?")) (role registry) (callable nil))
    (00011101 (surfaces (sa "na-adhika?") (sym "<=") (uk "не-більше?") (ukr "не-більше?")) (role registry) (callable nil))
    (00011110 (surfaces (sa "na-hīna?") (sym ">=") (uk "не-менше?") (ukr "не-менше?")) (role registry) (callable nil))
    (00011111 (surfaces (en "nondecreasing-from?") (ukr "неспадне-починаючи-з?")) (role registry) (callable nil))
    (00100000 (surfaces (en "nonincreasing-from?") (ukr "незростаюче-починаючи-з?")) (role registry) (callable nil))
    (00100001 (surfaces (en "not") (sa "na") (uk "хибне?") (ukr "хибне?")) (role registry) (callable nil))
    (00100010 (surfaces (en "equal?") (sa "tulya?") (uk "однакові?") (ukr "однакові?")) (role registry) (callable nil))
    (00100011 (surfaces (en "symbol?") (sa "nāman?") (uk "символ?") (ukr "символ?")) (role registry) (callable nil))
    (00100100 (surfaces (en "string?") (sa "śabda?") (uk "текст?") (ukr "текст?")) (role registry) (callable nil))
    (00100101 (surfaces (en "string<?") (sa "śabda-hīna?") (uk "текст-передує?") (ukr "текст-передує?")) (role registry) (callable nil))
    (00100110 (surfaces (en "numeric-buffer?") (uk "числовий-буфер?") (ukr "числовий-буфер?")) (role registry) (callable nil))
    (00100111 (surfaces (en "list") (sa "śreṇī") (uk "список") (ukr "список")) (role registry) (callable nil))
    (00101000 (surfaces (en "length") (sa "pramāṇa") (uk "довжина") (ukr "довжина")) (role registry) (callable nil))
    (00101001 (surfaces (en "append") (sa "saṅkalana") (uk "приєднати") (ukr "приєднати")) (role registry) (callable nil))
    (00101010 (surfaces (en "reverse") (sa "viloma") (uk "зворот") (ukr "зворот")) (role registry) (callable nil))
    (00101011 (surfaces (en "nth") (sa "kramāṅka") (uk "елемент-списку-за-індексом") (ukr "елемент-списку-за-індексом")) (role registry) (callable nil))
    (00101100 (surfaces (en "member?") (sa "sambaddha?") (uk "значення-у-списку?") (ukr "значення-у-списку?")) (role registry) (callable nil))
    (00101101 (surfaces (en "assoc") (sa "saṃbandha") (uk "знайти-за-ключем") (ukr "знайти-за-ключем")) (role registry) (callable nil))
    (00101110 (surfaces (en "pair") (sa "dvandva") (uk "пара") (ukr "пара")) (role registry) (callable nil))
    (00101111 (surfaces (en "second") (sa "dvitīya") (uk "друге") (ukr "друге")) (role registry) (callable nil))
    (00110000 (surfaces (en "third") (sa "tṛtīya") (uk "третє") (ukr "третє")) (role registry) (callable nil))
    (00110001 (surfaces (en "fourth") (sa "caturtha") (uk "четверте") (ukr "четверте")) (role registry) (callable nil))
    (00110010 (surfaces (en "fifth") (sa "pañcama") (uk "п'яте") (ukr "п'яте")) (role registry) (callable nil))
    (00110011 (surfaces (en "caar") (ukr "перше-від-першого")) (role registry) (callable nil))
    (00110100 (surfaces (en "cadr") (ukr "перше-від-решти")) (role registry) (callable nil))
    (00110101 (surfaces (en "cddr") (ukr "решта-від-решти")) (role registry) (callable nil))
    (00110110 (surfaces (en "cadddr") (ukr "перше-після-трьох-решт")) (role registry) (callable nil))
    (00110111 (surfaces (en "map") (sa "āvartana") (uk "відобразити") (ukr "відобразити")) (role registry) (callable nil))
    (00111000 (surfaces (en "filter") (sa "kalpana") (uk "відсіяти") (ukr "відсіяти")) (role registry) (callable nil))
    (00111001 (surfaces (en "reduce") (sa "saṅgraha") (uk "згорнути") (ukr "згорнути")) (role registry) (callable nil))
    (00111010 (surfaces (en "string-append") (sa "śabdasaṃyoga") (uk "зчепити") (ukr "зчепити")) (role registry) (callable nil))
    (00111011 (surfaces (en "string-length") (sa "śabdapramāṇa") (uk "довжина-тексту") (ukr "довжина-тексту")) (role registry) (callable nil))
    (00111100 (surfaces (en "string-empty?") (sa "śūnya?") (uk "текст-порожній?") (ukr "порожній-текст?")) (role registry) (callable nil))
    (00111101 (surfaces (en "string-prefix?") (sa "pūrva?") (uk "префікс-тексту?") (ukr "текст-починається-з?")) (role registry) (callable nil))
    (00111110 (surfaces (en "string-contains?") (sa "śabdasambaddha?") (uk "фрагмент-у-тексті?") (ukr "фрагмент-у-тексті?")) (role registry) (callable nil))
    (00111111 (surfaces (en "string-first") (sa "prathamavarṇa") (uk "перший-символ-тексту") (ukr "перший-символ-тексту")) (role registry) (callable nil))
    (01000000 (surfaces (en "string-rest") (sa "śeṣavarṇa") (uk "решта-символів-тексту") (ukr "решта-символів-тексту")) (role registry) (callable nil))
    (01000001 (surfaces (en "string-slice") (sa "cheda") (uk "відрізати") (ukr "відрізати")) (role registry) (callable nil))
    (01000010 (surfaces (en "symbol->string") (sa "nāman-śabda") (uk "символ-у-текст") (ukr "символ-у-текст")) (role registry) (callable nil))
    (01000011 (surfaces (en "string->symbol") (sa "śabda-nāman") (uk "текст-у-символ") (ukr "текст-у-символ")) (role registry) (callable nil))
    (01000100 (surfaces (en "codepoint->string") (sa "varṇa-śabda") (uk "кодова-точка-у-текст") (ukr "кодова-точка-у-текст")) (role registry) (callable nil))
    (01000101 (surfaces (en "string->codepoint") (sa "śabda-varṇa") (uk "текст-у-кодову-точку") (ukr "текст-у-кодову-точку")) (role registry) (callable nil))
    (01000110 (surfaces (en "number->string") (sa "saṅkhyā-śabda") (uk "число-у-текст") (ukr "число-у-текст")) (role registry) (callable nil))
    (01000111 (surfaces (en "digit->string") (ukr "цифра-у-текст")) (role registry) (callable nil))
    (01001000 (surfaces (en "print") (sa "mudraṇa") (uk "друкувати") (ukr "друкувати")) (role registry) (callable nil))
    (01001001 (surfaces (en "princ") (sa "darśana") (uk "показати") (ukr "показати")) (role registry) (callable nil))
    (01001010 (surfaces (en "read") (sa "pāṭhana") (uk "прочитати") (ukr "прочитати")) (role registry) (callable nil))
    (01001011 (surfaces (en "read-all") (sa "pāṭhana-sarva") (uk "прочитати-усе") (ukr "прочитати-усе")) (role registry) (callable nil))
    (01001100 (surfaces (en "write-to-string") (sa "likhana") (uk "значення-у-текст") (ukr "значення-у-текст")) (role registry) (callable nil))
    (01001101 (surfaces (en "eval") (sa "vicāraṇa") (uk "обчислити") (ukr "обчислити")) (role registry) (callable nil))
    (01001110 (surfaces (en "env") (sa "āśraya") (uk "середовище") (ukr "середовище")) (role registry) (callable nil))
    (01001111 (surfaces (en "vector") (sa "samūha") (uk "вектор") (ukr "вектор")) (role registry) (callable nil))
    (01010000 (surfaces (en "make-vector") (sa "samūha-nirmāṇa") (uk "створити-вектор") (ukr "створити-вектор")) (role registry) (callable nil))
    (01010001 (surfaces (en "vector-length") (sa "samūha-pramāṇa") (uk "довжина-вектора") (ukr "довжина-вектора")) (role registry) (callable nil))
    (01010010 (surfaces (en "vector-ref") (sa "samūha-āvartana") (uk "елемент-вектора") (ukr "елемент-вектора")) (role registry) (callable nil))
    (01010011 (surfaces (en "vector-set!") (uk "встановити-елемент-вектора!") (ukr "встановити-елемент-вектора!")) (role registry) (callable nil))
    (01010100 (surfaces (en "i32-buffer") (ukr "буфер-32-бітних-цілих-зі-знаком")) (role registry) (callable nil))
    (01010101 (surfaces (en "f32-buffer") (ukr "буфер-32-бітних-чисел-з-плавною-комою")) (role registry) (callable nil))
    (01010110 (surfaces (en "numeric-buffer-type") (ukr "тип-числового-буфера")) (role registry) (callable nil))
    (01010111 (surfaces (en "numeric-buffer-length") (ukr "довжина-числового-буфера")) (role registry) (callable nil))
    (01011000 (surfaces (en "numeric-buffer-ref") (ukr "елемент-числового-буфера")) (role registry) (callable nil))
    (01011001 (surfaces (en "numeric-buffer-map") (ukr "відобразити-числовий-буфер")) (role registry) (callable nil))
    (01011010 (surfaces (en "mono-ns") (sa "kāla-mono") (uk "монотонний-нс") (ukr "монотонний-час-у-наносекундах")) (role registry) (callable nil))
    (01011011 (surfaces (en "unix-time-now") (sa "kāla-unix") (uk "поточний-юнікс-час") (ukr "поточний-юнікс-час")) (role registry) (callable nil))
    (01011100 (surfaces (en "ntp-query-raw") (ukr "сирий-запит-мережевого-часу")) (role registry) (callable nil))
    (01011101 (surfaces (en "timezone-declarations-raw") (ukr "сирі-декларації-часових-поясів")) (role registry) (callable nil))
    (01011110 (surfaces (en "utc-now") (sa "kāla-adya") (uk "поточний-всч") (ukr "поточний-всесвітній-координований-час")) (role registry) (callable nil))
    (01011111 (surfaces (en "utc-from-unix") (uk "всч-із-юнікс") (ukr "всесвітній-координований-час-із-часу-юнікс")) (role registry) (callable nil))
    (01100000 (surfaces (en "unix-time-observation->utc") (uk "юнікс-спостереження-у-всч") (ukr "спостереження-часу-юнікс-у-всесвітній-координований-час")) (role registry) (callable nil))
    (01100001 (surfaces (en "milliseconds-from-nanoseconds") (sa "kāla-millisecondāni") (uk "мілісекунди-із-наносекунд") (ukr "мілісекунди-із-наносекунд")) (role registry) (callable nil))
    (01100010 (surfaces (en "mono-ms") (sa "kāla-mono-ms") (uk "монотонний-мс") (ukr "монотонний-час-у-мілісекундах")) (role registry) (callable nil))
    (01100011 (surfaces (en "timezone-name") (sa "deśa-kāla-nāma") (uk "назва-часового-поясу") (ukr "назва-часового-поясу")) (role registry) (callable nil))
    (01100100 (surfaces (en "timezone-detect") (sa "deśa-kāla-jñāna") (uk "визначити-часовий-пояс") (ukr "визначити-часовий-пояс")) (role registry) (callable nil))
    (01100101 (surfaces (en "timezone-offset-seconds") (sa "deśa-kāla-śeṣa") (uk "зміщення-часового-поясу-в-секундах") (ukr "зміщення-часового-поясу-в-секундах")) (role registry) (callable nil))
    (01100110 (surfaces (en "deadline-reached?") (sa "avadhi-gatā?") (uk "дедлайн-досягнуто?") (ukr "граничний-час-досягнуто?")) (role registry) (callable nil))
    (01100111 (surfaces (en "deadline-reached-at?") (sa "avadhi-gatā-kadā?") (uk "дедлайн-досягнуто-на-момент?") (ukr "граничний-час-досягнуто-на-момент?")) (role registry) (callable nil))
    (01101000 (surfaces (en "elapsed-ns") (sa "atīta-ns") (uk "минуло-нс") (ukr "минуло-наносекунд")) (role registry) (callable nil))
    (01101001 (surfaces (en "deadline-from") (sa "avadhi-nirmāṇa") (uk "дедлайн-від") (ukr "граничний-час-від")) (role registry) (callable nil))
    (01101010 (surfaces (en "deadline-after-ns") (sa "avadhi-anantara-ns") (uk "дедлайн-через-нс") (ukr "граничний-час-через-наносекунди")) (role registry) (callable nil))
    (01101011 (surfaces (en "internet-time-sync") (uk "запитати-інтернет-час") (ukr "синхронізувати-час-через-інтернет")) (role registry) (callable nil))
    (01101100 (surfaces (en "map-empty") (sa "kośa-śūnya") (uk "порожня-карта") (ukr "порожня-карта")) (role registry) (callable nil))
    (01101101 (surfaces (en "map-get") (sa "kośa-grahaṇa") (uk "отримати-з-карти") (ukr "отримати-з-карти")) (role registry) (callable nil))
    (01101110 (surfaces (en "map-insert") (sa "kośa-niveśana") (uk "вставити-в-карту") (ukr "вставити-в-карту")) (role registry) (callable nil))
    (01101111 (surfaces (en "map-contains?") (sa "kośa-sambaddha?") (uk "ключ-у-карті?") (ukr "ключ-у-карті?")) (role registry) (callable nil))
    (01110000 (surfaces (en "map->list") (sa "kośa-śreṇī") (uk "карта-у-список") (ukr "карта-у-список")) (role registry) (callable nil))
    (01110001 (surfaces (en "vec-empty") (sa "samūha-śūnya") (uk "порожній-вектор") (ukr "порожній-вектор")) (role registry) (callable nil))
    (01110010 (surfaces (en "vec-conj") (sa "samūha-yukti") (uk "додати-до-вектора") (ukr "додати-до-вектора")) (role registry) (callable nil))
    (01110011 (surfaces (en "vec-count") (sa "samūha-gaṇana") (uk "розмір-вектора") (ukr "розмір-вектора")) (role registry) (callable nil))
    (01110100 (surfaces (en "vec-nth") (sa "samūha-kramāṅka") (uk "елемент-вектора-за-індексом") (ukr "елемент-вектора-за-індексом")) (role registry) (callable nil))
    (01110101 (surfaces (en "vec->list") (sa "samūha-śreṇī") (uk "вектор-у-список") (ukr "вектор-у-список")) (role registry) (callable nil))
    (01110110 (surfaces (en "vec-from-list") (sa "śreṇī-samūha") (uk "вектор-із-списку") (ukr "вектор-із-списку")) (role registry) (callable nil))
    (01110111 (surfaces (en "is-fact?") (sa "jñāna-satya?") (uk "факт?") (ukr "факт?")) (role registry) (callable nil))
    (01111000 (surfaces (en "describe") (sa "varṇana") (uk "описати") (ukr "описати")) (role registry) (callable nil))
    (01111001 (surfaces (en "collect-facts-about") (sa "jñāna-saṅgraha") (uk "зібрати-факти-про") (ukr "зібрати-факти-про")) (role registry) (callable nil))
    (01111010 (surfaces (en "contains-atom?") (sa "aṇu-sambaddha?") (uk "атом-у-списку?") (ukr "атом-у-списку?")) (role registry) (callable nil))
    (01111011 (surfaces (en "forward-in") (sa "abhimukha-anumāna") (uk "пряме-виведення") (ukr "пряме-виведення")) (role registry) (callable nil))
    (01111100 (surfaces (en "reason-in") (sa "anumāna") (uk "логічний-висновок") (ukr "логічний-висновок")) (role registry) (callable nil))
    (01111101 (surfaces (en "check-conflict") (sa "virodha-parīkṣā") (uk "конфлікт?") (ukr "є-конфлікт?")) (role registry) (callable nil))
    (01111110 (surfaces (en "module-known?") (uk "модуль-відомий?") (ukr "модуль-відомий?")) (role registry) (callable nil))
    (01111111 (surfaces (en "module-clauses-now") (uk "поточні-клаузи-модуля") (ukr "поточні-клаузи-модуля")) (role registry) (callable nil))
    (10000000 (surfaces (en "prove-goal") (sa "siddhi-sādhana") (uk "довести-мету") (ukr "довести-мету")) (role registry) (callable nil))
    (10000001 (surfaces (en "prove-goals") (sa "siddhi-sādhana-sarva") (uk "довести-мети") (ukr "довести-мети")) (role registry) (callable nil))
    (10000010 (surfaces (en "explain-proof") (sa "siddhi-vyākhyā") (uk "пояснити-доведення") (ukr "пояснити-доведення")) (role registry) (callable nil))
    (10000011 (surfaces (en "source-of") (sa "siddhi-mūla") (uk "джерело-доведення") (ukr "джерело-доведення")) (role registry) (callable nil))
    (10000100 (surfaces (en "provenance") (sa "utpatti") (uk "походження") (ukr "походження")) (role registry) (callable nil))
    (10000101 (surfaces (en "reason") (sa "tarka") (uk "міркування") (ukr "міркування")) (role registry) (callable nil))
    (10000110 (surfaces (en "reason-explain") (sa "tarka-vyākhyā") (uk "пояснити-міркування") (ukr "пояснити-міркування")) (role registry) (callable nil))
    (10000111 (surfaces (en "unify") (sa "ekīkaraṇa") (uk "уніфікувати") (ukr "уніфікувати")) (role registry) (callable nil))
    (10001000 (surfaces (en "logic-var") (sa "tarka-cihna") (uk "логічна-змінна") (ukr "логічна-змінна")) (role registry) (callable nil))
    (10001001 (surfaces (en "var?") (sa "cihna?") (uk "змінна?") (ukr "змінна?")) (role registry) (callable nil))
    (10001010 (surfaces (en "apply-subst") (sa "pratyāroha") (uk "підставити") (ukr "підставити")) (role registry) (callable nil))
    (10001011 (surfaces (en "walk") (sa "vicāraṇa-gamana") (uk "розіменувати") (ukr "розіменувати")) (role registry) (callable nil))
    (10001100 (surfaces (en "occurs-check") (sa "parivṛtti-parīkṣā") (uk "змінна-зустрічається?") (ukr "змінна-зустрічається?")) (role registry) (callable nil))
    (10001101 (surfaces (en "claim?") (sa "pratyaya?") (uk "твердження?") (ukr "твердження?")) (role registry) (callable nil))
    (10001110 (surfaces (en "claim-statement") (sa "pratyaya-vākya") (uk "зміст-твердження") (ukr "зміст-твердження")) (role registry) (callable nil))
    (10001111 (surfaces (en "claim-review") (sa "pratyaya-parīkṣā") (uk "стан-розгляду-твердження") (ukr "стан-розгляду-твердження")) (role registry) (callable nil))
    (10010000 (surfaces (en "evidence?") (sa "pramāṇa?") (uk "доказ?") (ukr "доказ?")) (role registry) (callable nil))
    (10010001 (surfaces (en "evidence-method") (sa "pramāṇa-vidhi") (uk "метод-доказу") (ukr "метод-доказу")) (role registry) (callable nil))
    (10010010 (surfaces (en "evidence-outcome") (sa "pramāṇa-phala") (uk "результат-доказу") (ukr "результат-доказу")) (role registry) (callable nil))
    (10010011 (surfaces (en "observation?") (sa "pratyakṣa?") (uk "спостереження?") (ukr "спостереження?")) (role registry) (callable nil))
    (10010100 (surfaces (en "observation-statement") (sa "pratyakṣa-vākya") (uk "зміст-спостереження") (ukr "зміст-спостереження")) (role registry) (callable nil))
    (10010101 (surfaces (en "intent?") (sa "saṅkalpa?") (uk "намір?") (ukr "намір?")) (role registry) (callable nil))
    (10010110 (surfaces (en "intent-goal") (sa "saṅkalpa-lakṣya") (uk "мета-наміру") (ukr "мета-наміру")) (role registry) (callable nil))
    (10010111 (surfaces (en "supporting-evidence") (sa "sahāya-pramāṇa") (uk "підтримувальний-доказ") (ukr "підтримувальний-доказ")) (role registry) (callable nil))
    (10011000 (surfaces (en "identity") (sa "svabhāva") (uk "без-змін") (ukr "повернути-без-змін")) (role registry) (callable nil))
    (10011001 (surfaces (en "gensym") (sa "nāman-nirmāṇa") (uk "генерувати-символ") (ukr "створити-унікальний-символ")) (role registry) (callable nil))
    (10011010 (surfaces (en "and") (uk "та") (ukr "та")) (role registry) (callable nil))
    (10011011 (surfaces (en "or") (uk "або") (ukr "або")) (role registry) (callable nil))
    (10011100 (surfaces (en "let") (uk "нехай") (ukr "нехай")) (role registry) (callable nil))
    (10011101 (surfaces (en "let*") (uk "нехай*") (ukr "нехай-послідовно")) (role registry) (callable nil))
    (10011110 (surfaces (sym "->") (ukr "ланцюжок-першого-аргументу")) (role registry) (callable nil))
    (10011111 (surfaces (sym "->>") (ukr "ланцюжок-останнього-аргументу")) (role registry) (callable nil))
    (10100000 (surfaces (en "json-parse") (ukr "розібрати-текст-формату-джейсон")) (role registry) (callable nil))
    (10100001 (surfaces (en "sha256-hex") (ukr "обчислити-хеш-ша-256-тексту-у-шістнадцятковому-записі")) (role registry) (callable nil))
    (10100010 (surfaces (en "process-run") (uk "запустити-процес") (ukr "запустити-процес")) (role registry) (callable nil))
    (10100011 (surfaces (en "tcp-read") (uk "прочитати-текст-з-з'єднання-протоколу-керування-передаванням") (ukr "прочитати-текст-з-з'єднання-протоколу-керування-передаванням")) (role registry) (callable nil))
    (10100100 (surfaces (en "tcp-write") (uk "записати-текст-у-з'єднання-протоколу-керування-передаванням") (ukr "записати-текст-у-з'єднання-протоколу-керування-передаванням")) (role registry) (callable nil))
    (10100101 (surfaces (en "tcp-listen") (uk "слухати-порт-протоколу-керування-передаванням") (ukr "слухати-порт-протоколу-керування-передаванням")) (role registry) (callable nil))
    (10100110 (surfaces (en "read-file") (uk "прочитати-файл") (ukr "прочитати-файл")) (role registry) (callable nil))
    (10100111 (surfaces (en "write-file") (uk "записати-файл") (ukr "записати-файл")) (role registry) (callable nil))
    (10101000 (surfaces (en "invoke") (uk "викликати") (ukr "викликати")) (role registry) (callable nil))
    (10101001 (surfaces (en "binary") (uk "двійковий") (ukr "двійковий")) (role registry) (callable nil))))
