//! Fail-closed semantic admission between macro expansion and IR lowering.
//!
//! This is intentionally a small gate, not a claim of complete my-lisp
//! semantic analysis.  It rejects source shapes for which CML would otherwise
//! emit a different program than the canonical evaluator.
//!
//! Contract 6.0 (my-lisp, ratified 2026-09-08): the finite Canon 0+7 surface
//! name set is RESERVED and unshadowable. Any binder (def / lambda / let)
//! that attempts to bind a Canon spelling fails as InvalidForm. This module
//! enforces that reservation before IR lowering. CML still claims only
//! language contract 2.0 globally; this is a targeted static rejection that
//! aligns binder behaviour with upstream without upgrading the full claim.

use crate::ast::{Expr, NumericBufferLiteral};
use std::collections::HashSet;
use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SemanticErrorKind {
    DuplicateParameter,
    UnsupportedSequentialBody,
    /// #f32(...) numeric buffer — no backend supports Buffer(F32).
    UnsupportedF32Buffer,
    /// Attempt to bind a reserved Canon 0+7 surface name (Contract 6.0).
    ReservedCanonName,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SemanticError {
    pub kind: SemanticErrorKind,
    pub detail: String,
}

impl fmt::Display for SemanticError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(formatter, "{:?}: {}", self.kind, self.detail)
    }
}

impl std::error::Error for SemanticError {}

/// Finite reserved Canon 0+7 surface spellings (EN / UK / SA / symbolic),
/// generated by build.rs (cml#9) from the real, vendored my-lisp
/// lib/surface/semantic-registry.wsm -- not hand-transcribed.
/// Matching is case-insensitive for Latin identifiers (`CANON_UPPER_SURFACES`,
/// matching CML IR's own target-symbol uppercasing convention); Ukrainian and
/// Sanskrit surfaces (`CANON_EXACT_SURFACES`) are matched exactly as written
/// (Unicode) -- these scripts have no meaningful case-folding relationship to
/// that convention. Empty list `()` is a ground value, not a binder name, so
/// it is absent.
fn is_reserved_canon_surface(name: &str) -> bool {
    crate::canon::is_canon_form(
        name,
        crate::canon::CANON_UPPER_SURFACES,
        crate::canon::CANON_EXACT_SURFACES,
    )
}

fn reject_if_reserved(name: &str) -> Result<(), SemanticError> {
    if is_reserved_canon_surface(name) {
        Err(SemanticError {
            kind: SemanticErrorKind::ReservedCanonName,
            detail: format!("canonical name is immutable · канонічне ім'я незмінне: {name}"),
        })
    } else {
        Ok(())
    }
}

pub fn analyze_program(exprs: &[Expr]) -> Result<(), SemanticError> {
    exprs.iter().try_for_each(analyze_expr)
}

pub fn analyze_expr(expr: &Expr) -> Result<(), SemanticError> {
    // #f32(...) numeric buffer — no backend supports Buffer(F32)
    if let Expr::NumericBuffer(NumericBufferLiteral::F32(_)) = expr {
        return Err(SemanticError {
            kind: SemanticErrorKind::UnsupportedF32Buffer,
            detail: "#f32(...) numeric buffer not supported (no backend supports F32 buffers)"
                .to_string(),
        });
    }

    let Expr::List(items) = expr else {
        return Ok(());
    };
    let Some(Expr::Symbol(head)) = items.first() else {
        return items.iter().try_for_each(analyze_expr);
    };

    match head.as_str() {
        // Quoted data has no binding or execution semantics to analyze.
        "quote" => {
            if items.len() > 1 {
                analyze_quoted(&items[1])
            } else {
                Ok(())
            }
        }
        "lambda" if items.len() >= 3 => analyze_lambda(&items[1], &items[2..]),
        "def" if items.len() >= 2 => analyze_def(&items[1..]),
        "let" if items.len() >= 2 => analyze_let(&items[1], &items[2..]),
        _ => items.iter().skip(1).try_for_each(analyze_expr),
    }
}

fn analyze_quoted(expr: &Expr) -> Result<(), SemanticError> {
    match expr {
        // A quoted string is data like any other quoted literal -- both
        // backends represent Ir::String/Quoted::Str (c_backend.rs's
        // TAG_STRING, compiler.rs's LOADSYM representational substitution),
        // so this no longer needs rejecting ahead of lowering.
        Expr::List(list) => list.iter().try_for_each(analyze_quoted),
        Expr::DottedList(list, tail) => {
            list.iter().try_for_each(analyze_quoted)?;
            analyze_quoted(tail)
        }
        _ => Ok(()),
    }
}

fn analyze_def(args: &[Expr]) -> Result<(), SemanticError> {
    if let Some(Expr::Symbol(name)) = args.first() {
        reject_if_reserved(name)?;
    }
    args.iter().skip(1).try_for_each(analyze_expr)
}

fn analyze_let(bindings_expr: &Expr, body: &[Expr]) -> Result<(), SemanticError> {
    if let Expr::List(bindings) = bindings_expr {
        for binding in bindings {
            if let Expr::List(pair) = binding {
                if let Some(Expr::Symbol(name)) = pair.first() {
                    reject_if_reserved(name)?;
                }
                // Analyse binding values.
                pair.iter().skip(1).try_for_each(analyze_expr)?;
            }
        }
    }
    body.iter().try_for_each(analyze_expr)
}

fn analyze_lambda(params: &Expr, body: &[Expr]) -> Result<(), SemanticError> {
    if body.len() > 1 {
        return Err(SemanticError {
            kind: SemanticErrorKind::UnsupportedSequentialBody,
            detail: format!(
                "lambda has {} body expressions; CML IR currently represents exactly one",
                body.len()
            ),
        });
    }

    let mut names = Vec::new();
    match params {
        Expr::List(fixed) => collect_parameter_names(fixed, &mut names),
        Expr::DottedList(fixed, rest) => {
            collect_parameter_names(fixed, &mut names);
            if let Expr::Symbol(name) = &**rest {
                names.push(name);
            }
        }
        Expr::Symbol(name) => names.push(name),
        _ => {}
    }

    let mut seen = HashSet::new();
    for name in names {
        // Contract 6.0: Canon surfaces cannot be lambda parameters.
        reject_if_reserved(name)?;

        // CML's current IR/backend symbol representation is uppercase.  Two
        // source names that collide after that normalization cannot be
        // compiled faithfully, even if their original spelling differs.
        let normalized = name.to_uppercase();
        if !seen.insert(normalized.clone()) {
            return Err(SemanticError {
                kind: SemanticErrorKind::DuplicateParameter,
                detail: format!("lambda parameter `{normalized}` is bound more than once"),
            });
        }
    }

    body.iter().try_for_each(analyze_expr)
}

fn collect_parameter_names<'a>(params: &'a [Expr], names: &mut Vec<&'a str>) {
    for param in params {
        if let Expr::Symbol(name) = param {
            names.push(name);
        }
    }
}

#[cfg(test)]
mod reserved_canon_unit {
    use super::*;

    #[test]
    fn latin_canon_names_are_reserved() {
        for name in [
            "car", "CAR", "Car", "quote", "cond", "atom", "eq", "cons", "cdr",
        ] {
            assert!(is_reserved_canon_surface(name), "{name}");
        }
    }

    #[test]
    fn ukrainian_canon_names_are_reserved() {
        for name in [
            "перше",
            "решта",
            "як-є",
            "атом?",
            "тотожне?",
            "сполучити",
            "за-умовою",
        ] {
            assert!(is_reserved_canon_surface(name), "{name}");
        }
    }

    #[test]
    fn sanskrit_canon_names_are_reserved() {
        for name in [
            "ādi", "śeṣa", "svarūpa", "aṇu", "abheda", "saṃyuj", "anukrama",
        ] {
            assert!(is_reserved_canon_surface(name), "{name}");
        }
    }

    #[test]
    fn ordinary_names_are_not_reserved() {
        for name in [
            "map",
            "length",
            "x",
            "f",
            "+",
            "numeric-buffer-map",
            "відобразити",
        ] {
            assert!(!is_reserved_canon_surface(name), "{name}");
        }
    }
}
